# provendb-verify
# Copyright (C) 2019  Southbank Software Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# @Author: guiguan, koustubhg
# @Date:   2019-01-29T16:05:51+11:00
# @Last modified by:   guiguan
# @Last modified time: 2019-03-05T13:14:05+11:00

version: "2"

services:
  tests:
    image: golang:1.12.3
    container_name: tests
    command: ["/bin/sh", "-c", "ls sdfsdf"]
    # "git config --global url.\"https://${GIT_ACCESS_TOKEN}:@github.com/\".insteadOf \"https://github.com/\" \
    # && cd /go/provendb-verify \
    # && make test",
    volumes:
      - $PWD/provendb-verify:/go/provendb-verify
