# provendb-verify
# Copyright (C) 2019  Southbank Software Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# @Author: guiguan, koustubhg
# @Date:   2019-01-29T13:58:17+11:00
# @Last modified by:   guiguan
# @Last modified time: 2019-04-02T15:52:27+11:00

# update pipeline:
# fly -t dev sp -c pipeline-deploy.yml -p provendb-verify-deploy

resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
  - name: slack-alert
    type: docker-image
    source:
      repository: southbanksoftware/concourse-slack-alert-resource
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: meta
    type: meta
  - name: slack
    type: slack-alert
    source:
      url: ((common.slack-webook-url))
  - name: github-status
    type: github-status
    source:
      repository: SouthbankSoftware/provendb-verify
      access_token: ((common.git-access-token))
      branch: master
      context: deploy
  - name: provendb-verify
    type: git
    check_every: 5m
    webhook_token: ((common.webhook-token))
    source:
      uri: https://github.com/SouthbankSoftware/provendb-verify.git
      branch: master
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: provendb-releases
    type: git
    source:
      uri: https://github.com/SouthbankSoftware/provendb-releases.git
      branch: master
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: version
    type: semver
    source:
      driver: gcs
      bucket: provendb-ci
      json_key: ((common.service-account))
      key: provendb-verify/version/version.txt
      initial_version: 1.0.0
  - name: release-darwin_amd64
    type: gcs-resource
    source:
      bucket: provendb-dev
      json_key: ((common.service-account))
      versioned_file: provendb-verify/provendb-verify_darwin_amd64
  - name: release-linux_amd64
    type: gcs-resource
    source:
      bucket: provendb-dev
      json_key: ((common.service-account))
      versioned_file: provendb-verify/provendb-verify_linux_amd64
  - name: release-windows_amd64
    type: gcs-resource
    source:
      bucket: provendb-dev
      json_key: ((common.service-account))
      versioned_file: provendb-verify/provendb-verify_windows_amd64.exe

jobs:
  - name: build-and-deploy
    serial: true
    plan:
      - get: provendb-verify
        trigger: true
      - put: github-status
        params:
          commit: provendb-verify
          state: pending
      - get: version
      - task: build
        file: provendb-verify/ci/task-build/task-build.yml
      - aggregate:
          - put: release-darwin_amd64
            params:
              file: provendb-verify/provendb-verify_darwin_amd64
          - put: release-linux_amd64
            params:
              file: provendb-verify/provendb-verify_linux_amd64
          - put: release-windows_amd64
            params:
              file: provendb-verify/provendb-verify_windows_amd64.exe
      - get: meta
      - get: provendb-releases
      - task: save-build-info
        file: provendb-verify/ci/task-save-build-info/task-save-build-info.yml
      - put: provendb-releases
        params:
          repository: provendb-releases
          rebase: true
      - put: version
        params:
          bump: patch
    on_failure:
      do:
        - put: slack
          params:
            alert_type: failed
            text: ((slack.guan))
        - put: github-status
          params:
            commit: provendb-verify
            state: failure
    on_abort:
      do:
        - put: slack
          params:
            alert_type: failed
            text: Aborted. ((slack.guan))
        - put: github-status
          params:
            commit: provendb-verify
            state: failure
    on_success:
      do:
        - put: slack
          params:
            alert_type: success
        - put: github-status
          params:
            commit: provendb-verify
            state: success
